import json
import os
import unittest
from contextlib import redirect_stdout
from io import StringIO

import LnkParse3

TARGET_DIR = os.path.join(os.path.dirname(__file__), 'samples')


class TestSamples(unittest.TestCase):
    def setUp(self):
        def assert_json(filename, expected):
            filepath = os.path.join(TARGET_DIR, filename)
            with open(filepath, 'rb') as indata:
                lnk = LnkParse3.lnk_file(indata)

            mock_stdout = StringIO()
            with redirect_stdout(mock_stdout):
                lnk.print_json()

            got = json.loads(mock_stdout.getvalue())
            self.assertDictEqual(got, expected)

        self.assert_json = assert_json

    def test_json(self):
        self.maxDiff = None

        self.assert_json('microsoft_example.lnk', {
            'data': {'relative_path': '.\\a.txt', 'working_directory': 'C:\\test'},
            'extra': {'DISTRIBUTED_LINK_TRACKER_BLOCK': {'birth_droid_file_identifier': 'ec46cd7b227fdd11949900137216874a',
                                                         'birth_droid_volume_identifier': '4078c79447fac746b3565c2dc6b6d115',
                                                         'droid_file_identifier': 'ec46cd7b227fdd11949900137216874a',
                                                         'droid_volume_identifier': '4078c79447fac746b3565c2dc6b6d115',
                                                         'length': 88,
                                                         'machine_identifier': 'chris-xps',
                                                         'size': 96,
                                                         'version': 0}},
            'header': {'accessed_time': '2008-09-13 05:27:17',
                       'creation_time': '2008-09-13 05:27:17',
                       'file_flags': ['FILE_ATTRIBUTE_ARCHIVE'],
                       'file_size': 0,
                       'guid': '0114020000000000c000000000000046',
                       'hotkey': 'UNSET - UNSET {0x0000}',
                       'icon_index': 0,
                       'link_flags': ['HasTargetIDList',
                                      'HasLinkInfo',
                                      'HasRelativePath',
                                      'HasWorkingDir',
                                      'IsUnicode',
                                      'EnableTargetMetadata'],
                       'modified_time': '2008-09-13 05:27:17',
                       'r_file_flags': 32,
                       'r_hotkey': 0,
                       'r_link_flags': 524443,
                       'windowstyle': 'SW_NORMAL'},
            'link_info': {'common_path_suffix': '',
                          'link_info_flags': 1,
                          'local_base_path': 'C:\\test\\a.txt',
                          'location': 'Local',
                          'location_info': {'drive_serial_number': '0x307a8a81',
                                            'drive_type': 'DRIVE_FIXED',
                                            'r_drive_type': 3,
                                            'volume_id_size': 17,
                                            'volume_label': '',
                                            'volume_label_offset': 16}},
            'target': {'items': [{'class': 'Root Folder',
                                  'guid': 'e04fd020ea3a6910a2d808002b30309d',
                                  'sort_index': 'My Computer'},
                                 {'class': 'Volume Item', 'data': 'C:\\', 'flags': '0xf'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 16,
                                  'file_size': 0,
                                  'flags': 'Is directory',
                                  'primary_name': 'test'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 32,
                                  'file_size': 0,
                                  'flags': 'Is file',
                                  'primary_name': 'a.txt'}],
                       'size': 189}
        })

        # TODO: AttributeError: 'NoneType' object has no attribute 'pop'
        # self.assert_json('lnk_failing.lnk', {})
        # self.assert_json('lnk_failing2.lnk', {})
        # self.assert_json('lnk_failing3.lnk', {})
        # self.assert_json('lnk_failing4.lnk', {})

        self.assert_json('lnk_success.lnk', {
            'data': {'command_line_arguments': 'no_ipcheck - username=05551112233 '
                                               'password=123456',
                     'relative_path': '.\\AnonymusBrowser.exe',
                     'working_directory': 'C:\\AnonymusBrowser-v2.0'},
            'extra': {'DISTRIBUTED_LINK_TRACKER_BLOCK': {'birth_droid_file_identifier': '6895cc0632bfea11aba1008cfaad700e',
                                                         'birth_droid_volume_identifier': '0279bf2eaaedd643a8551512e2babff2',
                                                         'droid_file_identifier': '6895cc0632bfea11aba1008cfaad700e',
                                                         'droid_volume_identifier': '0279bf2eaaedd643a8551512e2babff2',
                                                         'length': 88,
                                                         'machine_identifier': 'desktop-73cl5qt',
                                                         'size': 96,
                                                         'version': 0},
                      'METADATA_PROPERTIES_BLOCK': {'format_id': 'ed30bdda43008947a7f8d013a4736622',
                                                    'size': 484,
                                                    'storage_size': 97,
                                                    'version': '0x53505331'}},
            'header': {'accessed_time': '2020-07-06 13:18:49',
                       'creation_time': '2020-07-04 07:51:57',
                       'file_flags': ['FILE_ATTRIBUTE_ARCHIVE'],
                       'file_size': 1490944,
                       'guid': '0114020000000000c000000000000046',
                       'hotkey': 'UNSET - UNSET {0x0000}',
                       'icon_index': 0,
                       'link_flags': ['HasTargetIDList',
                                      'HasLinkInfo',
                                      'HasRelativePath',
                                      'HasWorkingDir',
                                      'HasArguments',
                                      'IsUnicode',
                                      'EnableTargetMetadata'],
                       'modified_time': '2020-07-06 13:18:49',
                       'r_file_flags': 32,
                       'r_hotkey': 0,
                       'r_link_flags': 524475,
                       'windowstyle': 'SW_NORMAL'},
            'link_info': {'common_path_suffix': '',
                          'link_info_flags': 1,
                          'local_base_path': 'C:\\AnonymusBrowser-v2.0\\AnonymusBrowser.exe',
                          'location': 'Local',
                          'location_info': {'drive_serial_number': '0xd215cbdb',
                                            'drive_type': 'DRIVE_FIXED',
                                            'r_drive_type': 3,
                                            'volume_id_size': 17,
                                            'volume_label': '',
                                            'volume_label_offset': 16}},
            'target': {'items': [{'class': 'Root Folder',
                                  'guid': 'e04fd020ea3a6910a2d808002b30309d',
                                  'sort_index': 'My Computer'},
                                 {'class': 'Volume Item', 'data': 'C:\\', 'flags': '0xf'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 16,
                                  'file_size': 0,
                                  'flags': 'Is directory',
                                  'primary_name': 'ANONYM~1.0'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 32,
                                  'file_size': 1490944,
                                  'flags': 'Is file',
                                  'primary_name': 'ANONYM~1.EXE'}],
                       'size': 279}
        })

        self.assert_json('lnk_success2.lnk', {
            'data': {'command_line_arguments': 'no_ipcheck no_resize',
                     'relative_path': '.\\AnonymusBrowser.exe',
                     'working_directory': 'C:\\AnonymusBrowser-v2.0'},
            'extra': {'DISTRIBUTED_LINK_TRACKER_BLOCK': {'birth_droid_file_identifier': '6895cc0632bfea11aba1008cfaad700e',
                                                         'birth_droid_volume_identifier': '0279bf2eaaedd643a8551512e2babff2',
                                                         'droid_file_identifier': '6895cc0632bfea11aba1008cfaad700e',
                                                         'droid_volume_identifier': '0279bf2eaaedd643a8551512e2babff2',
                                                         'length': 88,
                                                         'machine_identifier': 'desktop-73cl5qt',
                                                         'size': 96,
                                                         'version': 0},
                      'METADATA_PROPERTIES_BLOCK': {'format_id': 'ed30bdda43008947a7f8d013a4736622',
                                                    'size': 484,
                                                    'storage_size': 97,
                                                    'version': '0x53505331'}},
            'header': {'accessed_time': '2020-07-06 13:18:49',
                       'creation_time': '2020-07-04 07:51:57',
                       'file_flags': ['FILE_ATTRIBUTE_ARCHIVE'],
                       'file_size': 1490944,
                       'guid': '0114020000000000c000000000000046',
                       'hotkey': 'UNSET - UNSET {0x0000}',
                       'icon_index': 0,
                       'link_flags': ['HasTargetIDList',
                                      'HasLinkInfo',
                                      'HasRelativePath',
                                      'HasWorkingDir',
                                      'HasArguments',
                                      'IsUnicode',
                                      'EnableTargetMetadata'],
                       'modified_time': '2020-07-06 13:18:49',
                       'r_file_flags': 32,
                       'r_hotkey': 0,
                       'r_link_flags': 524475,
                       'windowstyle': 'SW_NORMAL'},
            'link_info': {'common_path_suffix': '',
                          'link_info_flags': 1,
                          'local_base_path': 'C:\\AnonymusBrowser-v2.0\\AnonymusBrowser.exe',
                          'location': 'Local',
                          'location_info': {'drive_serial_number': '0xd215cbdb',
                                            'drive_type': 'DRIVE_FIXED',
                                            'r_drive_type': 3,
                                            'volume_id_size': 17,
                                            'volume_label': '',
                                            'volume_label_offset': 16}},
            'target': {'items': [{'class': 'Root Folder',
                                  'guid': 'e04fd020ea3a6910a2d808002b30309d',
                                  'sort_index': 'My Computer'},
                                 {'class': 'Volume Item', 'data': 'C:\\', 'flags': '0xf'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 16,
                                  'file_size': 0,
                                  'flags': 'Is directory',
                                  'primary_name': 'ANONYM~1.0'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 32,
                                  'file_size': 1490944,
                                  'flags': 'Is file',
                                  'primary_name': 'ANONYM~1.EXE'}],
                       'size': 279}
        })

        self.assert_json('lnk_success3.lnk', {
            'data': {'relative_path': '..\\..\\..\\Program Files '
                                      '(x86)\\HDZB_USBKEY_NEW1G\\HDZB_USBKEY_NEW1G.exe',
                     'working_directory': 'C:\\Program Files (x86)\\Mozilla Firefox'},
            'extra': {'DISTRIBUTED_LINK_TRACKER_BLOCK': {'birth_droid_file_identifier': '06eac9a3847aea11affc9bbabfbed054',
                                                         'birth_droid_volume_identifier': '96c86bde486d594588f3cb1f7258f3bb',
                                                         'droid_file_identifier': '06eac9a3847aea11affc9bbabfbed054',
                                                         'droid_volume_identifier': '96c86bde486d594588f3cb1f7258f3bb',
                                                         'length': 88,
                                                         'machine_identifier': 'officepc01',
                                                         'size': 96,
                                                         'version': 0},
                      'KNOWN_FOLDER_LOCATION_BLOCK': {'known_folder_id': 'ef405a7cfba0fc4b874ac0f2e0b9fa8e',
                                                      'offset': 193,
                                                      'size': 28},
                      'METADATA_PROPERTIES_BLOCK': {'format_id': 'e28a5846bc4c3843bbfc139326986dce',
                                                    'size': 153,
                                                    'storage_size': 141,
                                                    'version': '0x53505331'},
                      'SPECIAL_FOLDER_LOCATION_BLOCK': {'offset': 193,
                                                        'size': 16,
                                                        'special_folder_id': 42}},
            'header': {'accessed_time': '2020-08-24 06:02:13',
                       'creation_time': '2020-08-05 15:33:04',
                       'file_flags': ['FILE_ATTRIBUTE_ARCHIVE'],
                       'file_size': 558080,
                       'guid': '0114020000000000c000000000000046',
                       'hotkey': 'UNSET - UNSET {0x0000}',
                       'icon_index': 0,
                       'link_flags': ['HasTargetIDList',
                                      'HasLinkInfo',
                                      'HasRelativePath',
                                      'HasWorkingDir',
                                      'IsUnicode'],
                       'modified_time': '2020-08-05 15:33:04',
                       'r_file_flags': 32,
                       'r_hotkey': 0,
                       'r_link_flags': 155,
                       'windowstyle': 'SW_NORMAL'},
            'link_info': {'common_path_suffix': '',
                          'link_info_flags': 1,
                          'local_base_path': 'C:\\Program Files '
                                             '(x86)\\HDZB_USBKEY_NEW1G\\HDZB_USBKEY_NEW1G.exe',
                          'location': 'Local',
                          'location_info': {'drive_serial_number': '0xa4685e10',
                                            'drive_type': 'DRIVE_FIXED',
                                            'r_drive_type': 3,
                                            'volume_id_size': 24,
                                            'volume_label': 'Windows',
                                            'volume_label_offset': 16}},
            'target': {'items': [{'class': 'Root Folder',
                                  'guid': 'e04fd020ea3a6910a2d808002b30309d',
                                  'sort_index': 'My Computer'},
                                 {'class': 'Volume Item', 'data': 'C:\\', 'flags': '0xf'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 17,
                                  'file_size': 0,
                                  'flags': 'Is directory',
                                  'primary_name': 'PROGRA~2'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 16,
                                  'file_size': 0,
                                  'flags': 'Is directory',
                                  'primary_name': 'HDZB_U~1'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 32,
                                  'file_size': 558080,
                                  'flags': 'Is file',
                                  'primary_name': 'HDZB_U~1.EXE'}],
                       'size': 415}
        })

        self.assert_json('lnk_success4.lnk', {
            'data': {'command_line_arguments': 'no_ipcheck',
                     'relative_path': '.\\AnonymusBrowser.exe',
                     'working_directory': 'C:\\AnonymusBrowser-v2.0'},
            'extra': {'DISTRIBUTED_LINK_TRACKER_BLOCK': {'birth_droid_file_identifier': '6895cc0632bfea11aba1008cfaad700e',
                                                         'birth_droid_volume_identifier': '0279bf2eaaedd643a8551512e2babff2',
                                                         'droid_file_identifier': '6895cc0632bfea11aba1008cfaad700e',
                                                         'droid_volume_identifier': '0279bf2eaaedd643a8551512e2babff2',
                                                         'length': 88,
                                                         'machine_identifier': 'desktop-73cl5qt',
                                                         'size': 96,
                                                         'version': 0},
                      'METADATA_PROPERTIES_BLOCK': {'format_id': 'ed30bdda43008947a7f8d013a4736622',
                                                    'size': 484,
                                                    'storage_size': 97,
                                                    'version': '0x53505331'}},
            'header': {'accessed_time': '2020-07-06 13:18:49',
                       'creation_time': '2020-07-04 07:51:57',
                       'file_flags': ['FILE_ATTRIBUTE_ARCHIVE'],
                       'file_size': 1490944,
                       'guid': '0114020000000000c000000000000046',
                       'hotkey': 'UNSET - UNSET {0x0000}',
                       'icon_index': 0,
                       'link_flags': ['HasTargetIDList',
                                      'HasLinkInfo',
                                      'HasRelativePath',
                                      'HasWorkingDir',
                                      'HasArguments',
                                      'IsUnicode',
                                      'EnableTargetMetadata'],
                       'modified_time': '2020-07-06 13:18:49',
                       'r_file_flags': 32,
                       'r_hotkey': 0,
                       'r_link_flags': 524475,
                       'windowstyle': 'SW_NORMAL'},
            'link_info': {'common_path_suffix': '',
                          'link_info_flags': 1,
                          'local_base_path': 'C:\\AnonymusBrowser-v2.0\\AnonymusBrowser.exe',
                          'location': 'Local',
                          'location_info': {'drive_serial_number': '0xd215cbdb',
                                            'drive_type': 'DRIVE_FIXED',
                                            'r_drive_type': 3,
                                            'volume_id_size': 17,
                                            'volume_label': '',
                                            'volume_label_offset': 16}},
            'target': {'items': [{'class': 'Root Folder',
                                  'guid': 'e04fd020ea3a6910a2d808002b30309d',
                                  'sort_index': 'My Computer'},
                                 {'class': 'Volume Item', 'data': 'C:\\', 'flags': '0xf'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 16,
                                  'file_size': 0,
                                  'flags': 'Is directory',
                                  'primary_name': 'ANONYM~1.0'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 32,
                                  'file_size': 1490944,
                                  'flags': 'Is file',
                                  'primary_name': 'ANONYM~1.EXE'}],
                       'size': 279}
        })

        self.assert_json('lnk_success5.lnk', {
            'data': {'command_line_arguments': 'no_resize',
                     'relative_path': '.\\AnonymusBrowser.exe',
                     'working_directory': 'C:\\AnonymusBrowser-v2.0'},
            'extra': {'DISTRIBUTED_LINK_TRACKER_BLOCK': {'birth_droid_file_identifier': '6895cc0632bfea11aba1008cfaad700e',
                                                         'birth_droid_volume_identifier': '0279bf2eaaedd643a8551512e2babff2',
                                                         'droid_file_identifier': '6895cc0632bfea11aba1008cfaad700e',
                                                         'droid_volume_identifier': '0279bf2eaaedd643a8551512e2babff2',
                                                         'length': 88,
                                                         'machine_identifier': 'desktop-73cl5qt',
                                                         'size': 96,
                                                         'version': 0},
                      'METADATA_PROPERTIES_BLOCK': {'format_id': 'ed30bdda43008947a7f8d013a4736622',
                                                    'size': 484,
                                                    'storage_size': 97,
                                                    'version': '0x53505331'}},
            'header': {'accessed_time': '2020-07-06 13:18:49',
                       'creation_time': '2020-07-04 07:51:57',
                       'file_flags': ['FILE_ATTRIBUTE_ARCHIVE'],
                       'file_size': 1490944,
                       'guid': '0114020000000000c000000000000046',
                       'hotkey': 'UNSET - UNSET {0x0000}',
                       'icon_index': 0,
                       'link_flags': ['HasTargetIDList',
                                      'HasLinkInfo',
                                      'HasRelativePath',
                                      'HasWorkingDir',
                                      'HasArguments',
                                      'IsUnicode',
                                      'EnableTargetMetadata'],
                       'modified_time': '2020-07-06 13:18:49',
                       'r_file_flags': 32,
                       'r_hotkey': 0,
                       'r_link_flags': 524475,
                       'windowstyle': 'SW_NORMAL'},
            'link_info': {'common_path_suffix': '',
                          'link_info_flags': 1,
                          'local_base_path': 'C:\\AnonymusBrowser-v2.0\\AnonymusBrowser.exe',
                          'location': 'Local',
                          'location_info': {'drive_serial_number': '0xd215cbdb',
                                            'drive_type': 'DRIVE_FIXED',
                                            'r_drive_type': 3,
                                            'volume_id_size': 17,
                                            'volume_label': '',
                                            'volume_label_offset': 16}},
            'target': {'items': [{'class': 'Root Folder',
                                  'guid': 'e04fd020ea3a6910a2d808002b30309d',
                                  'sort_index': 'My Computer'},
                                 {'class': 'Volume Item', 'data': 'C:\\', 'flags': '0xf'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 16,
                                  'file_size': 0,
                                  'flags': 'Is directory',
                                  'primary_name': 'ANONYM~1.0'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 32,
                                  'file_size': 1490944,
                                  'flags': 'Is file',
                                  'primary_name': 'ANONYM~1.EXE'}],
                       'size': 279}
        })

        self.assert_json('lnk_success6.lnk', {
            'data': {'command_line_arguments': '/c start _ & _\\DeviceManager.exe & exit',
                     'icon_location': 'shell32.dll',
                     'working_directory': 'B:\\'},
            'extra': {'DISTRIBUTED_LINK_TRACKER_BLOCK': {'birth_droid_file_identifier': 'd3d3853cc9e5ea11abb04c72b91387bc',
                                                         'birth_droid_volume_identifier': '2a3dc1e9b0b69f4396b8480f5acbca8c',
                                                         'droid_file_identifier': 'd3d3853cc9e5ea11abb04c72b91387bc',
                                                         'droid_volume_identifier': '2a3dc1e9b0b69f4396b8480f5acbca8c',
                                                         'length': 88,
                                                         'machine_identifier': 'w-51511',
                                                         'size': 96,
                                                         'version': 0},
                      'ENVIRONMENTAL_VARIABLES_LOCATION_BLOCK': {'size': 788,
                                                                 'target_ansi': '%windir%\\system32\\cmd.exe',
                                                                 'target_unicode': '%'},
                      'KNOWN_FOLDER_LOCATION_BLOCK': {'known_folder_id': '774ec11ae7025d4eb7442eb1ae5198b7',
                                                      'offset': 213,
                                                      'size': 28},
                      'METADATA_PROPERTIES_BLOCK': {'format_id': 'e28a5846bc4c3843bbfc139326986dce',
                                                    'size': 153,
                                                    'storage_size': 141,
                                                    'version': '0x53505331'},
                      'SPECIAL_FOLDER_LOCATION_BLOCK': {'offset': 213,
                                                        'size': 16,
                                                        'special_folder_id': 37}},
            'header': {'accessed_time': '2018-12-28 22:06:00',
                       'creation_time': '2018-12-28 22:06:00',
                       'file_flags': ['FILE_ATTRIBUTE_ARCHIVE'],
                       'file_size': 302592,
                       'guid': '0114020000000000c000000000000046',
                       'hotkey': 'UNSET - UNSET {0x0000}',
                       'icon_index': 9,
                       'link_flags': ['HasTargetIDList',
                                      'HasLinkInfo',
                                      'HasWorkingDir',
                                      'HasArguments',
                                      'HasIconLocation',
                                      'IsUnicode',
                                      'HasExpString'],
                       'modified_time': '2010-11-20 10:17:02',
                       'r_file_flags': 32,
                       'r_hotkey': 0,
                       'r_link_flags': 755,
                       'windowstyle': 'SW_SHOWMINNOACTIVE'},
            'link_info': {'common_path_suffix': '',
                          'link_info_flags': 1,
                          'local_base_path': 'C:\\Windows\\System32\\cmd.exe',
                          'location': 'Local',
                          'location_info': {'drive_serial_number': '0x9606dc0f',
                                            'drive_type': 'DRIVE_FIXED',
                                            'r_drive_type': 3,
                                            'volume_id_size': 23,
                                            'volume_label': 'Disk-C',
                                            'volume_label_offset': 16}},
            'target': {'items': [{'class': 'Root Folder',
                                  'guid': 'e04fd020ea3a6910a2d808002b30309d',
                                  'sort_index': 'My Computer'},
                                 {'class': 'Volume Item', 'data': 'C:\\', 'flags': '0xf'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 16,
                                  'file_size': 0,
                                  'flags': 'Is directory',
                                  'primary_name': 'Windows'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 16,
                                  'file_size': 0,
                                  'flags': 'Is directory',
                                  'primary_name': 'System32'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 32,
                                  'file_size': 302592,
                                  'flags': 'Is file',
                                  'primary_name': 'cmd.exe'}],
                       'size': 297}
        })

        self.assert_json('lnk_success7.lnk', {
            'data': {'command_line_arguments': 'no_ipcheck no_resize username=05551112233 '
                                               'password=123456',
                     'relative_path': '.\\AnonymusBrowser.exe',
                     'working_directory': 'C:\\AnonymusBrowser-v2.0'},
            'extra': {'DISTRIBUTED_LINK_TRACKER_BLOCK': {'birth_droid_file_identifier': '6895cc0632bfea11aba1008cfaad700e',
                                                         'birth_droid_volume_identifier': '0279bf2eaaedd643a8551512e2babff2',
                                                         'droid_file_identifier': '6895cc0632bfea11aba1008cfaad700e',
                                                         'droid_volume_identifier': '0279bf2eaaedd643a8551512e2babff2',
                                                         'length': 88,
                                                         'machine_identifier': 'desktop-73cl5qt',
                                                         'size': 96,
                                                         'version': 0},
                      'METADATA_PROPERTIES_BLOCK': {'format_id': 'ed30bdda43008947a7f8d013a4736622',
                                                    'size': 484,
                                                    'storage_size': 97,
                                                    'version': '0x53505331'}},
            'header': {'accessed_time': '2020-07-06 13:18:49',
                       'creation_time': '2020-07-04 07:51:57',
                       'file_flags': ['FILE_ATTRIBUTE_ARCHIVE'],
                       'file_size': 1490944,
                       'guid': '0114020000000000c000000000000046',
                       'hotkey': 'UNSET - UNSET {0x0000}',
                       'icon_index': 0,
                       'link_flags': ['HasTargetIDList',
                                      'HasLinkInfo',
                                      'HasRelativePath',
                                      'HasWorkingDir',
                                      'HasArguments',
                                      'IsUnicode',
                                      'EnableTargetMetadata'],
                       'modified_time': '2020-07-06 13:18:49',
                       'r_file_flags': 32,
                       'r_hotkey': 0,
                       'r_link_flags': 524475,
                       'windowstyle': 'SW_NORMAL'},
            'link_info': {'common_path_suffix': '',
                          'link_info_flags': 1,
                          'local_base_path': 'C:\\AnonymusBrowser-v2.0\\AnonymusBrowser.exe',
                          'location': 'Local',
                          'location_info': {'drive_serial_number': '0xd215cbdb',
                                            'drive_type': 'DRIVE_FIXED',
                                            'r_drive_type': 3,
                                            'volume_id_size': 17,
                                            'volume_label': '',
                                            'volume_label_offset': 16}},
            'target': {'items': [{'class': 'Root Folder',
                                  'guid': 'e04fd020ea3a6910a2d808002b30309d',
                                  'sort_index': 'My Computer'},
                                 {'class': 'Volume Item', 'data': 'C:\\', 'flags': '0xf'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 16,
                                  'file_size': 0,
                                  'flags': 'Is directory',
                                  'primary_name': 'ANONYM~1.0'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 32,
                                  'file_size': 1490944,
                                  'flags': 'Is file',
                                  'primary_name': 'ANONYM~1.EXE'}],
                       'size': 279}
        })

        self.assert_json('lnk_success8.lnk', {
            'data': {'command_line_arguments': 'no_resize username=05551112233 '
                                               'password=123456',
                     'relative_path': '.\\AnonymusBrowser.exe',
                     'working_directory': 'C:\\AnonymusBrowser-v2.0'},
            'extra': {'DISTRIBUTED_LINK_TRACKER_BLOCK': {'birth_droid_file_identifier': '6895cc0632bfea11aba1008cfaad700e',
                                                         'birth_droid_volume_identifier': '0279bf2eaaedd643a8551512e2babff2',
                                                         'droid_file_identifier': '6895cc0632bfea11aba1008cfaad700e',
                                                         'droid_volume_identifier': '0279bf2eaaedd643a8551512e2babff2',
                                                         'length': 88,
                                                         'machine_identifier': 'desktop-73cl5qt',
                                                         'size': 96,
                                                         'version': 0},
                      'METADATA_PROPERTIES_BLOCK': {'format_id': 'ed30bdda43008947a7f8d013a4736622',
                                                    'size': 484,
                                                    'storage_size': 97,
                                                    'version': '0x53505331'}},
            'header': {'accessed_time': '2020-07-06 13:18:49',
                       'creation_time': '2020-07-04 07:51:57',
                       'file_flags': ['FILE_ATTRIBUTE_ARCHIVE'],
                       'file_size': 1490944,
                       'guid': '0114020000000000c000000000000046',
                       'hotkey': 'UNSET - UNSET {0x0000}',
                       'icon_index': 0,
                       'link_flags': ['HasTargetIDList',
                                      'HasLinkInfo',
                                      'HasRelativePath',
                                      'HasWorkingDir',
                                      'HasArguments',
                                      'IsUnicode',
                                      'EnableTargetMetadata'],
                       'modified_time': '2020-07-06 13:18:49',
                       'r_file_flags': 32,
                       'r_hotkey': 0,
                       'r_link_flags': 524475,
                       'windowstyle': 'SW_NORMAL'},
            'link_info': {'common_path_suffix': '',
                          'link_info_flags': 1,
                          'local_base_path': 'C:\\AnonymusBrowser-v2.0\\AnonymusBrowser.exe',
                          'location': 'Local',
                          'location_info': {'drive_serial_number': '0xd215cbdb',
                                            'drive_type': 'DRIVE_FIXED',
                                            'r_drive_type': 3,
                                            'volume_id_size': 17,
                                            'volume_label': '',
                                            'volume_label_offset': 16}},
            'target': {'items': [{'class': 'Root Folder',
                                  'guid': 'e04fd020ea3a6910a2d808002b30309d',
                                  'sort_index': 'My Computer'},
                                 {'class': 'Volume Item', 'data': 'C:\\', 'flags': '0xf'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 16,
                                  'file_size': 0,
                                  'flags': 'Is directory',
                                  'primary_name': 'ANONYM~1.0'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 32,
                                  'file_size': 1490944,
                                  'flags': 'Is file',
                                  'primary_name': 'ANONYM~1.EXE'}],
                       'size': 279}
        })

        self.assert_json('lnk_with_broken_link_info.lnk', {
            'data': {'relative_path': '..\\..\\..\\..\\..\\..\\Program Files\\xt\\xt.exe',
                     'working_directory': 'C:\\Program Files\\xt'},
            'extra': {'DISTRIBUTED_LINK_TRACKER_BLOCK': {'birth_droid_file_identifier': 'fde6604d6cf7ea119d939a6cb2227e78',
                                                         'birth_droid_volume_identifier': '182a76f68e337448b4d806de16586e7a',
                                                         'droid_file_identifier': 'fde6604d6cf7ea119d939a6cb2227e78',
                                                         'droid_volume_identifier': '182a76f68e337448b4d806de16586e7a',
                                                         'length': 88,
                                                         'machine_identifier': 'minwinpc',
                                                         'size': 96,
                                                         'version': 0},
                      'METADATA_PROPERTIES_BLOCK': {'format_id': 'b1166d44ad8d7048a748402ea43d788c',
                                                    'size': 69,
                                                    'storage_size': 57,
                                                    'version': '0x53505331'}},
            'header': {'accessed_time': '2020-09-16 00:58:43',
                       'creation_time': '2017-03-22 14:59:50',
                       'file_flags': ['FILE_ATTRIBUTE_ARCHIVE'],
                       'file_size': 40960,
                       'guid': '0114020000000000c000000000000046',
                       'hotkey': 'UNSET - UNSET {0x0000}',
                       'icon_index': 0,
                       'link_flags': ['HasTargetIDList',
                                      'HasRelativePath',
                                      'HasWorkingDir',
                                      'IsUnicode'],
                       'modified_time': '2016-06-28 17:39:33',
                       'r_file_flags': 32,
                       'r_hotkey': 0,
                       'r_link_flags': 153,
                       'windowstyle': 'SW_NORMAL'},
            'link_info': {},
            'target': {'items': [{'class': 'Root Folder',
                                  'guid': 'e04fd020ea3a6910a2d808002b30309d',
                                  'sort_index': 'My Computer'},
                                 {'class': 'Volume Item', 'data': 'C:\\', 'flags': '0xf'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 17,
                                  'file_size': 0,
                                  'flags': 'Is directory',
                                  'primary_name': 'PROGRA~1'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 16,
                                  'file_size': 0,
                                  'flags': 'Is directory',
                                  'primary_name': 'xt'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 32,
                                  'file_size': 40960,
                                  'flags': 'Is file',
                                  'primary_name': 'xt.exe'}],
                       'size': 343}
        })

        self.assert_json('lnk_with_decoding_error.lnk', {
            'data': {'relative_path': '.\\.CSV file'},
            'extra': {'DISTRIBUTED_LINK_TRACKER_BLOCK': {'birth_droid_file_identifier': '64fab6945aecea119a2e30e1717a583b',
                                                         'birth_droid_volume_identifier': 'bcba12567b8d2a4fa17aa2996cd50b5d',
                                                         'droid_file_identifier': '64fab6945aecea119a2e30e1717a583b',
                                                         'droid_volume_identifier': 'bcba12567b8d2a4fa17aa2996cd50b5d',
                                                         'length': 88,
                                                         'machine_identifier': 'desktop-crtgl03',
                                                         'size': 96,
                                                         'version': 0},
                      'METADATA_PROPERTIES_BLOCK': {'format_id': 'ed30bdda43008947a7f8d013a4736622',
                                                    'size': 791,
                                                    'storage_size': 277,
                                                    'version': '0x53505331'}},
            'header': {'accessed_time': '2020-09-02 19:46:37',
                       'creation_time': '2020-09-02 19:30:21',
                       'file_flags': ['FILE_ATTRIBUTE_DIRECTORY'],
                       'file_size': 4096,
                       'guid': '0114020000000000c000000000000046',
                       'hotkey': 'UNSET - UNSET {0x0000}',
                       'icon_index': 0,
                       'link_flags': ['HasTargetIDList',
                                      'HasLinkInfo',
                                      'HasRelativePath',
                                      'IsUnicode',
                                      'EnableTargetMetadata'],
                       'modified_time': '2020-09-02 19:46:37',
                       'r_file_flags': 16,
                       'r_hotkey': 0,
                       'r_link_flags': 524427,
                       'windowstyle': 'SW_NORMAL'},
            'link_info': {'common_path_suffix': '',
                          'link_info_flags': 1,
                          'local_base_path': 'C:\\Users\\Ibrahim\\Desktop\\PostDoc\\20190101 '
                                             '- 20191231 KU Leuven MD '
                                             'SPICY\\publications\\02_Majd\\Majd Py '
                                             'FT-IR\\.CSV file',
                          'location': 'Local',
                          'location_info': {'drive_serial_number': '0xc684b7e0',
                                            'drive_type': 'DRIVE_FIXED',
                                            'r_drive_type': 3,
                                            'volume_id_size': 17,
                                            'volume_label': '',
                                            'volume_label_offset': 16}},
            'target': {'items': [{'class': 'Root Folder',
                                  'guid': 'e04fd020ea3a6910a2d808002b30309d',
                                  'sort_index': 'My Computer'},
                                 {'class': 'Volume Item',
                                  'data': '\x80:Ì¿´,ÛLB°)\x7fé\x9a\x87ÆAV',
                                  'flags': '0xe'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 16,
                                  'file_size': 0,
                                  'flags': 'Is directory',
                                  'primary_name': 'PostDoc'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 16,
                                  'file_size': 0,
                                  'flags': 'Is directory',
                                  'primary_name': '201901~1'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 16,
                                  'file_size': 0,
                                  'flags': 'Is directory',
                                  'primary_name': 'PUBLIC~1'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 16,
                                  'file_size': 0,
                                  'flags': 'Is directory',
                                  'primary_name': '02_Majd'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 16,
                                  'file_size': 0,
                                  'flags': 'Is directory',
                                  'primary_name': 'MAJDPY~1'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 16,
                                  'file_size': 0,
                                  'flags': 'Is directory',
                                  'primary_name': 'CSVFIL~1'}],
                       'size': 654}
        })

        self.assert_json('lnk_with_decoding_error2.lnk', {
            'data': {'command_line_arguments': '/C .\\WindowsServices\\movemenoreg.vbs',
                     'icon_location': '%windir%\\system32\\SHELL32.dll'},
            'extra': {'DISTRIBUTED_LINK_TRACKER_BLOCK': {'birth_droid_file_identifier': 'f9ac30eaccb9e0118806bc5ff4204af6',
                                                         'birth_droid_volume_identifier': '067c1e0cf5e7c34ca6eefb36391163ac',
                                                         'droid_file_identifier': 'f9ac30eaccb9e0118806bc5ff4204af6',
                                                         'droid_volume_identifier': '067c1e0cf5e7c34ca6eefb36391163ac',
                                                         'length': 88,
                                                         'machine_identifier': 'dubay-¯ª',
                                                         'size': 96,
                                                         'version': 0},
                      'ENVIRONMENTAL_VARIABLES_LOCATION_BLOCK': {'size': 788,
                                                                 'target_ansi': '%COMSPEC%',
                                                                 'target_unicode': '%'},
                      'KNOWN_FOLDER_LOCATION_BLOCK': {'known_folder_id': '774ec11ae7025d4eb7442eb1ae5198b7',
                                                      'offset': 213,
                                                      'size': 28},
                      'METADATA_PROPERTIES_BLOCK': {'format_id': 'e28a5846bc4c3843bbfc139326986dce',
                                                    'size': 153,
                                                    'storage_size': 141,
                                                    'version': '0x53505331'},
                      'SPECIAL_FOLDER_LOCATION_BLOCK': {'offset': 213,
                                                        'size': 16,
                                                        'special_folder_id': 37}},
            'header': {'accessed_time': '2010-11-21 12:23:55',
                       'creation_time': '2010-11-21 12:23:55',
                       'file_flags': ['FILE_ATTRIBUTE_ARCHIVE'],
                       'file_size': 345088,
                       'guid': '0114020000000000c000000000000046',
                       'hotkey': 'UNSET - UNSET {0x0000}',
                       'icon_index': 7,
                       'link_flags': ['HasTargetIDList',
                                      'HasLinkInfo',
                                      'HasArguments',
                                      'HasIconLocation',
                                      'IsUnicode',
                                      'HasExpString'],
                       'modified_time': '2010-11-21 12:23:55',
                       'r_file_flags': 32,
                       'r_hotkey': 0,
                       'r_link_flags': 739,
                       'windowstyle': 'SW_SHOWMINNOACTIVE'},
            'link_info': {'common_path_suffix': '',
                          'link_info_flags': 1,
                          'local_base_path': 'C:\\Windows\\System32\\cmd.exe',
                          'location': 'Local',
                          'location_info': {'drive_serial_number': '0x42b6ef87',
                                            'drive_type': 'DRIVE_FIXED',
                                            'r_drive_type': 3,
                                            'volume_id_size': 17,
                                            'volume_label': '',
                                            'volume_label_offset': 16}},
            'target': {'items': [{'class': 'Root Folder',
                                  'guid': 'e04fd020ea3a6910a2d808002b30309d',
                                  'sort_index': 'My Computer'},
                                 {'class': 'Volume Item', 'data': 'C:\\', 'flags': '0xf'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 16,
                                  'file_size': 0,
                                  'flags': 'Is directory',
                                  'primary_name': 'Windows'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 16,
                                  'file_size': 0,
                                  'flags': 'Is directory',
                                  'primary_name': 'System32'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 32,
                                  'file_size': 345088,
                                  'flags': 'Is file',
                                  'primary_name': 'cmd.exe'}],
                       'size': 297}
        })

        self.assert_json('lnk_with_decoding_error3.lnk', {
            'data': {'icon_location': '%SystemRoot%\\System32\\SHELL32.dll',
                     'relative_path': '.\\Mod for Pixelmon\\Error Fix.bat',
                     'working_directory': 'C:\\Users\\8<0\\Desktop\\PixelMod\\Mod for '
                                          'Pixelmon'},
            'extra': {'DISTRIBUTED_LINK_TRACKER_BLOCK': {'birth_droid_file_identifier': '0cbffc392eedea11aef6b0fc36c1f116',
                                                         'birth_droid_volume_identifier': 'f2189efe52d7a04b92a3382c109743b5',
                                                         'droid_file_identifier': '0cbffc392eedea11aef6b0fc36c1f116',
                                                         'droid_volume_identifier': 'f2189efe52d7a04b92a3382c109743b5',
                                                         'length': 88,
                                                         'machine_identifier': 'desktop-9ai08qd',
                                                         'size': 96,
                                                         'version': 0},
                      'METADATA_PROPERTIES_BLOCK': {'format_id': 'ed30bdda43008947a7f8d013a4736622',
                                                    'size': 592,
                                                    'storage_size': 157,
                                                    'version': '0x53505331'}},
            'header': {'accessed_time': '2020-09-03 23:59:20',
                       'creation_time': '2020-09-03 01:27:18',
                       'file_flags': ['FILE_ATTRIBUTE_ARCHIVE',
                                      'FILE_ATTRIBUTE_COMPRESSED'],
                       'file_size': 135,
                       'guid': '0114020000000000c000000000000046',
                       'hotkey': 'UNSET - UNSET {0x0000}',
                       'icon_index': 29,
                       'link_flags': ['HasTargetIDList',
                                      'HasLinkInfo',
                                      'HasRelativePath',
                                      'HasWorkingDir',
                                      'HasIconLocation',
                                      'IsUnicode',
                                      'EnableTargetMetadata'],
                       'modified_time': '2020-09-03 01:27:24',
                       'r_file_flags': 2080,
                       'r_hotkey': 0,
                       'r_link_flags': 524507,
                       'windowstyle': 'SW_NORMAL'},
            'link_info': {'common_path_suffix': 'Äèìà\\Desktop\\PixelMod\\Mod for '
                                                'Pixelmon\\Error Fix.bat',
                          'link_info_flags': 3,
                          'local_base_path': 'C:\\Users\\',
                          'location': 'Local',
                          'location_info': {'drive_serial_number': '0xe60d92cf',
                                            'drive_type': 'DRIVE_FIXED',
                                            'r_drive_type': 3,
                                            'volume_id_size': 24,
                                            'volume_label': 'Windows',
                                            'volume_label_offset': 16}},
            'target': {'items': [{'class': 'Root Folder',
                                  'guid': 'e04fd020ea3a6910a2d808002b30309d',
                                  'sort_index': 'My Computer'},
                                 {'class': 'Volume Item',
                                  'data': '\x80:Ì¿´,ÛLB°)\x7fé\x9a\x87ÆA&',
                                  'flags': '0xe'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 2064,
                                  'file_size': 0,
                                  'flags': 'Is directory',
                                  'primary_name': 'PixelMod'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 2064,
                                  'file_size': 0,
                                  'flags': 'Is directory',
                                  'primary_name': 'MODFOR~1'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 2080,
                                  'file_size': 135,
                                  'flags': 'Is file',
                                  'primary_name': 'ERRORF~1.BAT'}],
                       'size': 380}
        })

        self.assert_json('lnk_with_invalid_date.lnk', {
            'data': {'relative_path': '.\\.git'},
            'extra': {'DISTRIBUTED_LINK_TRACKER_BLOCK': {'birth_droid_file_identifier': '81a3fc4755cfea11a768a0d3c124012a',
                                                         'birth_droid_volume_identifier': '44f84655bbda9644a6540c6775d519cb',
                                                         'droid_file_identifier': '81a3fc4755cfea11a768a0d3c124012a',
                                                         'droid_volume_identifier': '44f84655bbda9644a6540c6775d519cb',
                                                         'length': 88,
                                                         'machine_identifier': 'r4pc5',
                                                         'size': 96,
                                                         'version': 0},
                      'METADATA_PROPERTIES_BLOCK': {'format_id': 'ed30bdda43008947a7f8d013a4736622',
                                                    'size': 539,
                                                    'storage_size': 161,
                                                    'version': '0x53505331'}},
            'header': {'accessed_time': '2020-07-27 01:14:03',
                       'creation_time': '2020-07-26 17:51:06',
                       'file_flags': ['FILE_ATTRIBUTE_HIDDEN', 'FILE_ATTRIBUTE_DIRECTORY'],
                       'file_size': 4096,
                       'guid': '0114020000000000c000000000000046',
                       'hotkey': 'UNSET - UNSET {0x0000}',
                       'icon_index': 0,
                       'link_flags': ['HasTargetIDList',
                                      'HasLinkInfo',
                                      'HasRelativePath',
                                      'IsUnicode',
                                      'EnableTargetMetadata'],
                       'modified_time': '2020-07-26 17:51:09',
                       'r_file_flags': 18,
                       'r_hotkey': 0,
                       'r_link_flags': 524427,
                       'windowstyle': 'SW_NORMAL'},
            'link_info': {'common_path_suffix': '',
                          'link_info_flags': 1,
                          'local_base_path': 'E:\\Razwan Ali\\REACT '
                                             'NATIVE\\React-Navigation-with-drawer\\.git',
                          'location': 'Local',
                          'location_info': {'drive_serial_number': '0x16a22e4e',
                                            'drive_type': 'DRIVE_FIXED',
                                            'r_drive_type': 3,
                                            'volume_id_size': 27,
                                            'volume_label': 'New Volume',
                                            'volume_label_offset': 16}},
            'target': {'items': [{'class': 'Root Folder',
                                  'guid': 'e04fd020ea3a6910a2d808002b30309d',
                                  'sort_index': 'My Computer'},
                                 {'class': 'Volume Item', 'data': 'E:\\', 'flags': '0xf'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 16,
                                  'file_size': 0,
                                  'flags': 'Is directory',
                                  'primary_name': 'Razwan Ali'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 16,
                                  'file_size': 0,
                                  'flags': 'Is directory',
                                  'primary_name': 'REACT NATIVE'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 16,
                                  'file_size': 0,
                                  'flags': 'Is directory',
                                  'primary_name': 'React-Navigation-with-drawer'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 18,
                                  'file_size': 0,
                                  'flags': 'Is directory',
                                  'primary_name': '.git'}],
                       'size': 473}
        })

        self.assert_json('lnk_with_invalid_date2.lnk', {
            'data': {'command_line_arguments': '/c ren cfsdaacdfawd\\*.vbss *.vbs &start '
                                               '\\cfsdaacdfawd\\aiasfacoiaksf.vbs&start '
                                               'explorer .android_secure&exit',
                     'icon_location': '%SystemRoot%\\System32\\shell32.dll'},
            'extra': {'KNOWN_FOLDER_LOCATION_BLOCK': {'known_folder_id': '774ec11ae7025d4eb7442eb1ae5198b7',
                                                      'offset': 213,
                                                      'size': 28},
                      'METADATA_PROPERTIES_BLOCK': {'format_id': 'e28a5846bc4c3843bbfc139326986dce',
                                                    'size': 153,
                                                    'storage_size': 141,
                                                    'version': '0x53505331'},
                      'SPECIAL_FOLDER_LOCATION_BLOCK': {'offset': 213,
                                                        'size': 16,
                                                        'special_folder_id': 37}},
            'header': {'accessed_time': '',
                       'creation_time': '',
                       'file_flags': [],
                       'file_size': 0,
                       'guid': '0114020000000000c000000000000046',
                       'hotkey': 'UNSET - UNSET {0x0000}',
                       'icon_index': 3,
                       'link_flags': ['HasTargetIDList',
                                      'HasArguments',
                                      'HasIconLocation',
                                      'IsUnicode'],
                       'modified_time': '',
                       'r_file_flags': 0,
                       'r_hotkey': 0,
                       'r_link_flags': 225,
                       'windowstyle': 'SW_SHOWMINNOACTIVE'},
            'link_info': {},
            'target': {'items': [{'class': 'Root Folder',
                                  'guid': 'e04fd020ea3a6910a2d808002b30309d',
                                  'sort_index': 'My Computer'},
                                 {'class': 'Volume Item', 'data': 'C:\\', 'flags': '0xf'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 16,
                                  'file_size': 0,
                                  'flags': 'Is directory',
                                  'primary_name': 'Windows'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 16,
                                  'file_size': 0,
                                  'flags': 'Is directory',
                                  'primary_name': 'system32'},
                                 {'class': 'File entry',
                                  'file_attribute_flags': 0,
                                  'file_size': 0,
                                  'flags': 'Is file',
                                  'primary_name': 'cmd.exe'}],
                       'size': 297}
        })

        self.assert_json('lnk_with_invalid_date3.lnk', {
            'data': {'relative_path': '.\\'},
            'extra': {'DISTRIBUTED_LINK_TRACKER_BLOCK': {'birth_droid_file_identifier': '2dcdf616f1e6ea11a184706655a5c7f0',
                                                         'birth_droid_volume_identifier': '00000000000000000000000000000000',
                                                         'droid_file_identifier': '2dcdf616f1e6ea11a184706655a5c7f0',
                                                         'droid_volume_identifier': '00000000000000000000000000000000',
                                                         'length': 88,
                                                         'machine_identifier': 'desktop-o6lerhr',
                                                         'size': 96,
                                                         'version': 0},
                      'METADATA_PROPERTIES_BLOCK': {'format_id': 'ed30bdda43008947a7f8d013a4736622',
                                                    'size': 430,
                                                    'storage_size': 133,
                                                    'version': '0x53505331'}},
            'header': {'accessed_time': '2020-09-13 00:35:19',
                       'creation_time': '2020-08-26 03:03:29',
                       'file_flags': ['FILE_ATTRIBUTE_READONLY',
                                      'FILE_ATTRIBUTE_DIRECTORY'],
                       'file_size': 4096,
                       'guid': '0114020000000000c000000000000046',
                       'hotkey': 'UNSET - UNSET {0x0000}',
                       'icon_index': 0,
                       'link_flags': ['HasTargetIDList',
                                      'HasLinkInfo',
                                      'HasRelativePath',
                                      'IsUnicode',
                                      'EnableTargetMetadata'],
                       'modified_time': '2020-09-11 20:46:36',
                       'r_file_flags': 17,
                       'r_hotkey': 0,
                       'r_link_flags': 524427,
                       'windowstyle': 'SW_NORMAL'},
            'link_info': {'common_path_suffix': '',
                          'link_info_flags': 1,
                          'local_base_path': 'C:\\Users\\Ïîëüçîâàòåëü\\Desktop\\\xa0',
                          'location': 'Local',
                          'location_info': {'drive_serial_number': '0x6f2abee',
                                            'drive_type': 'DRIVE_FIXED',
                                            'r_drive_type': 3,
                                            'volume_id_size': 17,
                                            'volume_label': '',
                                            'volume_label_offset': 16}},
            'target': {'items': [{'class': 'File entry',
                                  'file_attribute_flags': 17,
                                  'file_size': 0,
                                  'flags': 'Is directory',
                                  'primary_name': '9DEC~1'}],
                       'size': 76}
        })


if __name__ == '__main__':
    unittest.main()

# flake8: noqa E501
